# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 671)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 0, 451, 671))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(469, 0, 331, 671))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.notest_list = QtWidgets.QListWidget(parent=self.verticalLayoutWidget)
        self.notest_list.setObjectName("notest_list")
        self.verticalLayout.addWidget(self.notest_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_note = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.add_note.setObjectName("add_note")
        self.horizontalLayout.addWidget(self.add_note)
        self.del_note = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.del_note.setObjectName("del_note")
        self.horizontalLayout.addWidget(self.del_note)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.save_note = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.save_note.setObjectName("save_note")
        self.verticalLayout.addWidget(self.save_note)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.tag_list = QtWidgets.QListWidget(parent=self.verticalLayoutWidget)
        self.tag_list.setObjectName("tag_list")
        self.verticalLayout.addWidget(self.tag_list)
        self.tag_input = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.tag_input.setObjectName("tag_input")
        self.verticalLayout.addWidget(self.tag_input)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_tag = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.add_tag.setObjectName("add_tag")
        self.horizontalLayout_3.addWidget(self.add_tag)
        self.del_tag = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.del_tag.setObjectName("del_tag")
        self.horizontalLayout_3.addWidget(self.del_tag)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.search_btb = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.search_btb.setObjectName("search_btb")
        self.verticalLayout.addWidget(self.search_btb)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "список нотаток"))
        self.add_note.setText(_translate("MainWindow", "+ нотатки"))
        self.del_note.setText(_translate("MainWindow", "- нотатки"))
        self.save_note.setText(_translate("MainWindow", "зберегти"))
        self.label_2.setText(_translate("MainWindow", "зписок тегів"))
        self.tag_input.setPlaceholderText(_translate("MainWindow", "тег"))
        self.add_tag.setText(_translate("MainWindow", "+ тег"))
        self.del_tag.setText(_translate("MainWindow", "- тег"))
        self.search_btb.setText(_translate("MainWindow", "шук нот по тегу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
